version: '3'

services:
  web:
    build: .
#    command: "python manage.py runserver 0.0.0.0:8000"
    command: "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
#      - ./:/usr/src/app/
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 8000
    ports:
      - "8000:8000"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6378:6379'
  db:
    image: postgres:latest
    container_name: db
    environment:
      - PD_DATA=/var/lib/postgresql/data
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8080
    ports:
      - "80:8080"
    depends_on:
      - web
volumes:
  pg_data:
  static_volume:
  media_volume: